apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
#  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /drupal-mysql-data
